@id("5cf54081-5c23-4188-a153-f6f862eefd55")
@nodeType("707")
WITH "ORDER_COUNTS" AS (
    SELECT
        MOD("ORDER_ID", 25) AS "NATION_KEY",
        COUNT(*) AS "ORDER_COUNT"
    FROM {{ ref('SRC', 'ORDERS_TEST') }}
    GROUP BY MOD("ORDER_ID", 25)
)
SELECT
     "NATION_KEY" AS "NATION_KEY",
     "ORDER_COUNT" AS "ORDER_COUNT"
FROM "ORDER_COUNTS"