@id("7aaec9bc-37a8-4c1c-8cc4-5a261794b511")
@nodeType("707")
SELECT
     "C_CUSTKEY" AS "C_CUSTKEY",
     "C_NAME" AS "C_NAME",
     "C_ADDRESS" AS "C_ADDRESS",
     "C_NATIONKEY" AS "C_NATIONKEY",
     "C_PHONE" AS "C_PHONE",
     "C_ACCTBAL" AS "C_ACCTBAL",
     "C_MKTSEGMENT" AS "C_MKTSEGMENT" @accepted_values("'AUTOMOBILE', 'BUILDING', 'FURNITURE', 'HOUSEHOLD', 'MACHINERY'"),
     "C_COMMENT" AS "C_COMMENT"
FROM {{ ref('SRC', 'CUSTOMER') }} "CUSTOMER"

