@id("1578b3e4-e328-49ea-950f-9c6195bd40cb")
@nodeType("707")
WITH "ORDER_COUNTS" AS (
    SELECT
        MOD("ORDER_ID", 25) AS "NATION_KEY",
        COUNT(*) AS "ORDER_COUNT",
        SUM("ORDER_ID") AS "ORDER_ID_SUM",
        AVG("ORDER_ID") AS "ORDER_ID_AVG",
        MIN("ORDER_ID") AS "ORDER_ID_MIN",
        MAX("ORDER_ID") AS "ORDER_ID_MAX"
    FROM {{ ref('SRC', 'ORDERS_TEST') }}
    GROUP BY MOD("ORDER_ID", 25)
)
SELECT
     "N"."N_NATIONKEY" AS "N_NATIONKEY" @notNull,
     "N"."N_NAME" AS "N_NAME",
     "N"."N_REGIONKEY" AS "N_REGIONKEY",
     "SUB"."ORDER_COUNT" AS "ORDER_COUNT",
     "SUB"."ORDER_ID_SUM" AS "ORDER_ID_SUM",
     "SUB"."ORDER_ID_AVG" AS "ORDER_ID_AVG",
     "SUB"."ORDER_ID_MIN" AS "ORDER_ID_MIN",
     "SUB"."ORDER_ID_MAX" AS "ORDER_ID_MAX"
FROM {{ ref('SRC', 'NATION_TEST') }} "N"
JOIN "ORDER_COUNTS" "SUB" ON "N"."N_NATIONKEY" = "SUB"."NATION_KEY"