@id("43727cea-041e-4f57-ba27-aaf24716ee46")
@nodeType("707")
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY",
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('TARGET', 'STG_NATION_TEST_VIEW') }} "STG_NATION_TEST_VIEW"