@id("16e55d17-9764-4c0c-8a81-266a5146a0e7")
@nodeType("710")
SELECT DISTINCT
    0 AS "DIM_NATION_KEY" @isSurrogateKey,
    N_NATIONKEY AS "N_NATIONKEY" @isBusinessKey,
    N_NAME AS "N_NAME" @isChangeTracking,
    N_REGIONKEY AS "N_REGIONKEY",
    N_COMMENT AS "N_COMMENT",
    1 AS "SYSTEM_VERSION" @isSystemVersion,
    'Y' AS "SYSTEM_CURRENT_FLAG" @isSystemCurrentFlag,
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate,
    CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE" @isSystemEndDate
FROM {{ ref("SRC", "NATION_TEST") }}
