@id("94602a76-c61e-48b5-94b5-c24f59773190")
@nodeType("e35d8015-545b-4150-942f-5168dcd2bea8")

WITH ALL_NATIONS AS (

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY1') }}

    UNION ALL

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY2') }}

)

SELECT
     NATIONS_SAMPLE."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     NATIONS_SAMPLE."N_NAME" AS "N_NAME" @description("name of country"),
     NATIONS_SAMPLE."N_REGIONKEY" AS "N_REGIONKEY",
     NATIONS_SAMPLE."N_COMMENT" AS "N_COMMENT" @defaultValue("NA"),
     NATIONS_SAMPLE."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" @isLastModifiedColumn,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate
FROM ALL_NATIONS "NATIONS_SAMPLE"