@id("b414aae5-b0b8-4d4a-9a36-32808bcc0e9a")
@nodeType("SQLWork")
@writeMode("truncateInsert")
SELECT
    UPPER(TRIM("EMPLOYEE_TRAINING"."EMPLOYEE_ID"))     AS "EMPLOYEE_ID"     @id("8008b9") @not_null,
    UPPER(TRIM("EMPLOYEE_TRAINING"."TRAINING_ID"))     AS "TRAINING_ID"     @id("5169a2") @not_null,
    "EMPLOYEE_TRAINING"."TRAINING_DATE"                AS "TRAINING_DATE"   @id("78a1f8") @not_null,
    UPPER(TRIM("EMPLOYEE_TRAINING"."TRAINING_STATUS")) AS "TRAINING_STATUS" @id("8bbd65"),
    UPPER(TRIM("EMPLOYEE_TRAINING"."TRAINING_TYPE"))   AS "TRAINING_TYPE"   @id("7f9ad9")
FROM {{ ref('SRC', 'EMPLOYEE_TRAINING') }} "EMPLOYEE_TRAINING"
WHERE "EMPLOYEE_TRAINING"."EMPLOYEE_ID" IS NOT NULL
  AND "EMPLOYEE_TRAINING"."TRAINING_ID" IS NOT NULL
