@id("64d9d636-bc1c-485c-9c93-06cea18b1014")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")

WITH ALL_TABLES AS (
     SELECT * FROM {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1"
     UNION
     SELECT * FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
)

SELECT
     ALL_TABLES."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     ALL_TABLES."N_NAME" AS "N_NAME" @isBusinessKey,
     ALL_TABLES."N_REGIONKEY" AS "N_REGIONKEY" @isChangeTracking,
     ALL_TABLES."N_COMMENT" AS "N_COMMENT" @isChangeTracking,
     ALL_TABLES."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     "DIM_MS_CT_SCD2_KEY"::NUMBER AS "DIM_MS_CT_SCD2_KEY" @isSurrogateKey,
     "SYSTEM_CURRENT_FLAG"::VARCHAR AS "SYSTEM_CURRENT_FLAG" @isSystemCurrentFlag,
     "SYSTEM_VERSION"::NUMBER AS "SYSTEM_VERSION" @isSystemVersion,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate,
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE" @isSystemEndDate
FROM ALL_TABLES