@id("e88ebc63-83b1-4516-b1f4-d0f3fc00e08b")
@nodeType("660")
@groupByAll(true)
@orderby(true)
@orderbycolumn("[object Object]", "desc")
WITH ALL_NATIONS AS(
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY" ,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" 
FROM {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1" 
UNION
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY" ,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
) 
SELECT
     0 AS "PSTG_NATION_COPY1_KEY",
     ALL_NATIONS."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     ALL_NATIONS."N_NAME" AS "N_NAME" @isChangeTracking,
     ALL_NATIONS."N_REGIONKEY" AS "N_REGIONKEY",
     ALL_NATIONS."N_COMMENT" AS "N_COMMENT",
     ALL_NATIONS."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     1 AS "SYSTEM_VERSION",
     'Y' AS "SYSTEM_CURRENT_FLAG",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE",
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE"
FROM ALL_NATIONS ALL_NATIONS
WHERE ALL_NATIONS.N_NATIONKEY = 2