@id("96f64142-945b-4c4f-9345-23cae78f1b99")
@nodeType("718")
@mergeStrategy("lastModified")
@description("Timestamp-based CDC SCD Type 1 line item dimension built on WRK_LINEITEM; a row whose LAST_MODIFIED_TS is newer than the stored value is overwritten in place, no history kept")
@tests("SELECT 1 FROM {{ this }} WHERE ABS(L_EXTENDEDPRICE * (1 - L_DISCOUNT) - L_NET_PRICE) > 0.01")
@tests("SELECT 1 FROM {{ this }} WHERE (L_RETURNFLAG = 'N') <> (L_RECEIPTDATE > DATE '1995-06-17') OR (L_LINESTATUS = 'O') <> (L_SHIPDATE > DATE '1995-06-17')")
@tests("SELECT 1 FROM {{ this }} GROUP BY L_ORDERKEY, L_LINENUMBER HAVING COUNT(*) > 1")
@tests("SELECT 1 FROM {{ this }} WHERE LAST_MODIFIED_TS <> GREATEST(L_SHIPDATE, L_COMMITDATE, L_RECEIPTDATE)::TIMESTAMP")
SELECT
    0                                                                                                                       AS "DIM_LINEITEM_LM_SCD1_KEY" @id("db0f14") @isSurrogateKey @description("Surrogate key of the line item row"),
    CAST("WRK_LINEITEM"."L_ORDERKEY" AS NUMBER(38,0))                                                                       AS "L_ORDERKEY"               @id("056a88") @isBusinessKey @not_null @min_value("1") @description("Order key (business key, part 1)"),
    CAST("WRK_LINEITEM"."L_LINENUMBER" AS NUMBER(38,0))                                                                     AS "L_LINENUMBER"             @id("ca4fe9") @isBusinessKey @not_null @min_max("1", "7") @description("Line number within the order (business key, part 2)"),
    CAST("WRK_LINEITEM"."L_PARTKEY" AS NUMBER(38,0))                                                                        AS "L_PARTKEY"                @id("5db6b2") @not_null @min_value("1") @description("Part key (FK to PART)"),
    CAST("WRK_LINEITEM"."L_SUPPKEY" AS NUMBER(38,0))                                                                        AS "L_SUPPKEY"                @id("d9f444") @not_null @min_value("1") @description("Supplier key (FK to SUPPLIER)"),
    CAST("WRK_LINEITEM"."L_QUANTITY" AS NUMBER(12,2))                                                                       AS "L_QUANTITY"               @id("ad4ebc") @not_null @min_max("1", "50") @description("Quantity ordered"),
    CAST("WRK_LINEITEM"."L_EXTENDEDPRICE" AS NUMBER(12,2))                                                                  AS "L_EXTENDEDPRICE"          @id("bbc2df") @not_null @min_value("0") @description("Extended price (quantity x part retail price)"),
    CAST("WRK_LINEITEM"."L_DISCOUNT" AS NUMBER(12,2))                                                                       AS "L_DISCOUNT"               @id("faf7bb") @not_null @min_max("0", "0.10") @description("Discount rate applied to the line"),
    CAST("WRK_LINEITEM"."L_TAX" AS NUMBER(12,2))                                                                            AS "L_TAX"                    @id("000775") @not_null @min_max("0", "0.08") @description("Tax rate applied to the line"),
    CAST("WRK_LINEITEM"."L_RETURNFLAG" AS VARCHAR(1))                                                                       AS "L_RETURNFLAG"             @id("8caff5") @not_null @accepted_values("'R', 'A', 'N'") @description("Return flag (R, A or N)"),
    CAST("WRK_LINEITEM"."L_LINESTATUS" AS VARCHAR(1))                                                                       AS "L_LINESTATUS"             @id("78665e") @not_null @accepted_values("'O', 'F'") @description("Line status (O = open, F = fulfilled)"),
    CAST("WRK_LINEITEM"."L_SHIPDATE" AS DATE)                                                                               AS "L_SHIPDATE"               @id("1479af") @not_null @min_max("DATE '1992-01-01'", "DATE '1999-12-31'") @relative_time("<=", "L_RECEIPTDATE") @description("Date the line was shipped"),
    CAST("WRK_LINEITEM"."L_COMMITDATE" AS DATE)                                                                             AS "L_COMMITDATE"             @id("d2096e") @not_null @min_max("DATE '1992-01-01'", "DATE '1999-12-31'") @description("Date the line was committed to ship"),
    CAST("WRK_LINEITEM"."L_RECEIPTDATE" AS DATE)                                                                            AS "L_RECEIPTDATE"            @id("1324d2") @not_null @min_max("DATE '1992-01-01'", "DATE '1999-12-31'") @description("Date the line was received"),
    CAST("WRK_LINEITEM"."L_SHIPINSTRUCT" AS VARCHAR(25))                                                                    AS "L_SHIPINSTRUCT"           @id("602c4a") @not_null @accepted_values("'DELIVER IN PERSON', 'COLLECT COD', 'NONE', 'TAKE BACK RETURN'") @description("Shipping instructions"),
    CAST("WRK_LINEITEM"."L_SHIPMODE" AS VARCHAR(10))                                                                        AS "L_SHIPMODE"               @id("62d619") @not_null @accepted_values("'AIR', 'FOB', 'MAIL', 'RAIL', 'REG AIR', 'SHIP', 'TRUCK'") @description("Shipping mode"),
    CAST("WRK_LINEITEM"."L_COMMENT" AS VARCHAR(44))                                                                         AS "L_COMMENT"                @id("17e0ce") @description("Free-text comment about the line"),
    CAST("WRK_LINEITEM"."L_NET_PRICE" AS NUMBER(18,4))                                                                      AS "L_NET_PRICE"              @id("384f70") @not_null @min_value("0") @description("Extended price after discount"),
    CAST("WRK_LINEITEM"."L_CHARGE" AS NUMBER(24,6))                                                                         AS "L_CHARGE"                 @id("575932") @not_null @min_value("0") @description("Extended price after discount, including tax"),
    CAST(GREATEST("WRK_LINEITEM"."L_SHIPDATE", "WRK_LINEITEM"."L_COMMITDATE", "WRK_LINEITEM"."L_RECEIPTDATE") AS TIMESTAMP) AS "LAST_MODIFIED_TS"         @id("c52a41") @lastModifiedTracking(1) @not_null @description("Latest of ship, commit and receipt date; a newer value than the stored one overwrites the row in place"),
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP)                                                                                    AS "SYSTEM_CREATE_DATE"       @id("a87bac") @isSystemCreateDate @not_null @description("Timestamp when the row was first inserted"),
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP)                                                                                    AS "SYSTEM_UPDATE_DATE"       @id("5bbfd3") @isSystemUpdateDate @not_null @relative_time(">=", "SYSTEM_CREATE_DATE") @description("Timestamp when the row was last inserted or overwritten")
FROM {{ ref('TARGET', 'WRK_LINEITEM') }} "WRK_LINEITEM"
