@id("bd4cb5e5-17cf-439b-b447-1dee833f1e0c")
@nodeType("707")
WITH ORDERS_CTE AS
(SELECT
     "ORDER_ID" AS "ORDER_ID",
     "CUSTOMER_NAME" COLLATE 'en-ci' AS "CUSTOMER_NAME" ,
     "ORDER_DATA" AS "ORDER_DATA"
FROM {{ ref('SRC', 'ORDERS_SAMPLE_FLAT') }} 
)
SELECT * FROM ORDERS_CTE
WHERE CUSTOMER_NAME COLLATE 'en-ci' = 'JOHN';
-- ORDER BY CUSTOMER_NAME COLLATE 'en-ci';