
@id("e01e2103-4dc0-4757-983d-bf8ba7f9cb3b")
@nodeType("6fda2820-4404-4b60-bad3-cf0edd7dab92")

WITH UNPIVOTED_FRUIT AS (

    SELECT
        FRUITNAME,
        NAME,
        QUANTITY
    FROM {{ ref('SRC', 'FRUITINVENTORY') }} "FRUITINVENTORY"
    UNPIVOT (
        QUANTITY
        FOR NAME IN (
            "STOREA",
            "STOREB"
        )
    ) AS UNPIVOTED

)

SELECT
    FRUITNAME::VARCHAR AS "FRUITNAME",
    NAME::VARCHAR    AS "STORE_NAME",
    QUANTITY::NUMBER AS "QUANTITY" 
FROM UNPIVOTED_FRUIT
