@id("50e4415f-e14d-4ead-8f3d-09661c008433")
@nodeType("e35d8015-545b-4150-942f-5168dcd2bea8")


@truncateBefore
@selectDistinct

WITH ALL_NATIONS AS (

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY1') }}

    UNION ALL

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY2') }}

)

SELECT
     0 AS "DIM_KEY" @isSurrogateKey,
     NATIONS."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     NATIONS."N_NAME" AS "N_NAME",
     NATIONS."N_REGIONKEY" AS "N_REGIONKEY",
     NATIONS."N_COMMENT" AS "N_COMMENT",
     NATIONS."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate,

FROM ALL_NATIONS "NATIONS"