@id("7043cff8-68b5-475d-b76c-dc08a25fd7a6")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")
SELECT
     {{NODE_NAME}}_KEY AS "MRG_NATION4_KEY",
     "N_NATIONKEY" AS "N_NATIONKEY",
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION') }} "NATION"