@id("abe23e91-96cf-4f63-831f-f188e4779daf")
@nodeType("718")
@mergeStrategy("lastModified")
@description("Timestamp-based CDC SCD Type 2 line item dimension built on WRK_LINEITEM; a row whose LAST_MODIFIED_TS is newer than the current version expires it and inserts a new version")
@tests("SELECT 1 FROM {{ this }} WHERE SYSTEM_CURRENT_FLAG = 'Y' GROUP BY L_ORDERKEY, L_LINENUMBER HAVING COUNT(*) > 1")
@tests("SELECT 1 FROM {{ this }} GROUP BY L_ORDERKEY, L_LINENUMBER, SYSTEM_VERSION HAVING COUNT(*) > 1")
@tests("SELECT 1 FROM {{ this }} WHERE (SYSTEM_CURRENT_FLAG = 'Y' AND SYSTEM_END_DATE <> '2999-12-31 00:00:00'::TIMESTAMP) OR (SYSTEM_CURRENT_FLAG = 'N' AND SYSTEM_END_DATE >= '2999-12-31 00:00:00'::TIMESTAMP)")
@tests("SELECT 1 FROM {{ this }} WHERE ABS(L_EXTENDEDPRICE * (1 - L_DISCOUNT) - L_NET_PRICE) > 0.01")
@tests("SELECT 1 FROM {{ this }} WHERE (L_RETURNFLAG = 'N') <> (L_RECEIPTDATE > DATE '1995-06-17') OR (L_LINESTATUS = 'O') <> (L_SHIPDATE > DATE '1995-06-17')")
SELECT
    0                                                                                                                       AS "DIM_LINEITEM_LM_SCD2_KEY" @id("68649e") @isSurrogateKey @description("Surrogate key of the line item version"),
    CAST("WRK_LINEITEM"."L_ORDERKEY" AS NUMBER(38,0))                                                                       AS "L_ORDERKEY"               @id("c5652a") @isBusinessKey @not_null @min_value("1") @description("Order key (business key, part 1)"),
    CAST("WRK_LINEITEM"."L_LINENUMBER" AS NUMBER(38,0))                                                                     AS "L_LINENUMBER"             @id("135fa5") @isBusinessKey @not_null @min_max("1", "7") @description("Line number within the order (business key, part 2)"),
    CAST("WRK_LINEITEM"."L_PARTKEY" AS NUMBER(38,0))                                                                        AS "L_PARTKEY"                @id("e33fe7") @not_null @min_value("1") @description("Part key (FK to PART)"),
    CAST("WRK_LINEITEM"."L_SUPPKEY" AS NUMBER(38,0))                                                                        AS "L_SUPPKEY"                @id("73e69b") @not_null @min_value("1") @description("Supplier key (FK to SUPPLIER)"),
    CAST("WRK_LINEITEM"."L_QUANTITY" AS NUMBER(12,2))                                                                       AS "L_QUANTITY"               @id("776359") @not_null @min_max("1", "50") @description("Quantity ordered"),
    CAST("WRK_LINEITEM"."L_EXTENDEDPRICE" AS NUMBER(12,2))                                                                  AS "L_EXTENDEDPRICE"          @id("1d6cb0") @not_null @min_value("0") @description("Extended price (quantity x part retail price)"),
    CAST("WRK_LINEITEM"."L_DISCOUNT" AS NUMBER(12,2))                                                                       AS "L_DISCOUNT"               @id("7e728d") @not_null @min_max("0", "0.10") @description("Discount rate applied to the line"),
    CAST("WRK_LINEITEM"."L_TAX" AS NUMBER(12,2))                                                                            AS "L_TAX"                    @id("dd18e6") @not_null @min_max("0", "0.08") @description("Tax rate applied to the line"),
    CAST("WRK_LINEITEM"."L_RETURNFLAG" AS VARCHAR(1))                                                                       AS "L_RETURNFLAG"             @id("ad74e1") @not_null @accepted_values("'R', 'A', 'N'") @description("Return flag (R, A or N)"),
    CAST("WRK_LINEITEM"."L_LINESTATUS" AS VARCHAR(1))                                                                       AS "L_LINESTATUS"             @id("d5ce49") @not_null @accepted_values("'O', 'F'") @description("Line status (O = open, F = fulfilled)"),
    CAST("WRK_LINEITEM"."L_SHIPDATE" AS DATE)                                                                               AS "L_SHIPDATE"               @id("c2518d") @not_null @min_max("DATE '1992-01-01'", "DATE '1999-12-31'") @relative_time("<=", "L_RECEIPTDATE") @description("Date the line was shipped"),
    CAST("WRK_LINEITEM"."L_COMMITDATE" AS DATE)                                                                             AS "L_COMMITDATE"             @id("2d8fce") @not_null @min_max("DATE '1992-01-01'", "DATE '1999-12-31'") @description("Date the line was committed to ship"),
    CAST("WRK_LINEITEM"."L_RECEIPTDATE" AS DATE)                                                                            AS "L_RECEIPTDATE"            @id("83e96a") @not_null @min_max("DATE '1992-01-01'", "DATE '1999-12-31'") @description("Date the line was received"),
    CAST("WRK_LINEITEM"."L_SHIPINSTRUCT" AS VARCHAR(25))                                                                    AS "L_SHIPINSTRUCT"           @id("613157") @not_null @accepted_values("'DELIVER IN PERSON', 'COLLECT COD', 'NONE', 'TAKE BACK RETURN'") @description("Shipping instructions"),
    CAST("WRK_LINEITEM"."L_SHIPMODE" AS VARCHAR(10))                                                                        AS "L_SHIPMODE"               @id("01288e") @not_null @accepted_values("'AIR', 'FOB', 'MAIL', 'RAIL', 'REG AIR', 'SHIP', 'TRUCK'") @description("Shipping mode"),
    CAST("WRK_LINEITEM"."L_COMMENT" AS VARCHAR(44))                                                                         AS "L_COMMENT"                @id("5773e8") @description("Free-text comment about the line"),
    CAST("WRK_LINEITEM"."L_NET_PRICE" AS NUMBER(18,4))                                                                      AS "L_NET_PRICE"              @id("9d3cc3") @not_null @min_value("0") @description("Extended price after discount"),
    CAST("WRK_LINEITEM"."L_CHARGE" AS NUMBER(24,6))                                                                         AS "L_CHARGE"                 @id("b18f08") @not_null @min_value("0") @description("Extended price after discount, including tax"),
    CAST(GREATEST("WRK_LINEITEM"."L_SHIPDATE", "WRK_LINEITEM"."L_COMMITDATE", "WRK_LINEITEM"."L_RECEIPTDATE") AS TIMESTAMP) AS "LAST_MODIFIED_TS"         @id("393458") @lastModifiedTracking(2) @not_null @description("Latest of ship, commit and receipt date; a newer value than the stored version expires it and inserts a new version"),
    1                                                                                                                       AS "SYSTEM_VERSION"           @id("b303b7") @isSystemVersion @not_null @min_value("1") @description("Version number of the line item, incremented on each newer LAST_MODIFIED_TS"),
    'Y'                                                                                                                     AS "SYSTEM_CURRENT_FLAG"      @id("e36410") @isSystemCurrentFlag @not_null @accepted_values("'Y', 'N'") @description("Y on the current version of the line item, N on expired versions"),
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP)                                                                                    AS "SYSTEM_CREATE_DATE"       @id("72d8d5") @isSystemCreateDate @not_null @description("Timestamp when this version was first inserted"),
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP)                                                                                    AS "SYSTEM_UPDATE_DATE"       @id("fa055d") @isSystemUpdateDate @not_null @relative_time(">=", "SYSTEM_CREATE_DATE") @description("Timestamp when this version was last inserted or expired"),
    CAST('2999-12-31 00:00:00' AS TIMESTAMP)                                                                                AS "SYSTEM_END_DATE"          @id("37d693") @isSystemEndDate @not_null @description("End of the validity window of this version; 2999-12-31 while current")
FROM {{ ref('TARGET', 'WRK_LINEITEM') }} "WRK_LINEITEM"
