@id("47f57bce-7b6d-4beb-8225-f6c3112ff167")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")

@materializationType("view")

SELECT
     NATION."N_NATIONKEY" AS "N_NATIONKEY",
     NATION."N_NAME" AS "N_NAME",
     NATION."N_REGIONKEY" AS "N_REGIONKEY",
     NATION."N_COMMENT" AS "N_COMMENT",
     NATION."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION"