@id("507d8d7f-41f6-4fc6-bc38-8c377668f2e3")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")

@treatNullAsCurrentTimestamp
@type2Dimension

WITH ALL_NATIONS AS (

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY1') }}

    UNION ALL

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY2') }}

)

SELECT
     NATIONS_SAMPLE."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     NATIONS_SAMPLE."N_NAME" AS "N_NAME" @description("name of country"),
     NATIONS_SAMPLE."N_REGIONKEY" AS "N_REGIONKEY",
     NATIONS_SAMPLE."N_COMMENT" AS "N_COMMENT" @defaultValue("NA"),
     NATIONS_SAMPLE."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" @isLastModifiedColumn,
     0 AS "SYSTEM_VERSION" @isSystemVersion @defaultValue("1"),
     '' AS "SYSTEM_CURRENT_FLAG" @isSystemCurrentFlag @defaultValue("Y"),
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate,
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE" @isSystemEndDate
FROM ALL_NATIONS "NATIONS_SAMPLE"