@id("c064e61e-b768-498c-984f-49a6b178a984")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")

WITH ALL_TABLES AS (
     SELECT * FROM {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1"
     UNION
     SELECT * FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
)

SELECT
     ALL_TABLES."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     ALL_TABLES."N_NAME" AS "N_NAME" @isBusinessKey,
     ALL_TABLES."N_REGIONKEY" AS "N_REGIONKEY",
     ALL_TABLES."N_COMMENT" AS "N_COMMENT",
     ALL_TABLES."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" @isLastModifiedColumn,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate
FROM ALL_TABLES