@id("6bb858cc-1f0b-4adf-9df6-1887afb54e37")
@nodeType("663")

WITH ALL_NATION AS
(
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY",
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "CREATED_TIME" AS "CREATED_TIME"
FROM {{ ref('SRC', 'NATION_TEST1') }} "NATION_TEST1"

UNION

SELECT
     "N_NATIONKEY" AS "N_NATIONKEY",
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "CREATED_TIME" AS "CREATED_TIME"
FROM {{ ref('SRC', 'NATION_TEST2') }} "NATION_TEST2"
)

SELECT *,
     1 AS "SYSTEM_VERSION",
     'Y' AS "SYSTEM_CURRENT_FLAG",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE",
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE"
FROM ALL_NATION