@id("404e88e8-69b9-4097-b9ae-712d6c253ebf")
@nodeType("e35d8015-545b-4150-942f-5168dcd2bea8")

WITH ALL_NATIONS AS (

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY1') }}

    UNION ALL

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY2') }}

)

SELECT
     0 AS "DIM_KEY" @isSurrogateKey,
     NATIONS_SAMPLE."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     NATIONS_SAMPLE."N_NAME" AS "N_NAME",
     NATIONS_SAMPLE."N_REGIONKEY" AS "N_REGIONKEY",
     NATIONS_SAMPLE."N_COMMENT" AS "N_COMMENT",
     NATIONS_SAMPLE."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate
FROM ALL_NATIONS "NATIONS_SAMPLE"