@id("88a1ccc0-8e3a-4f6f-86f4-af8b344f6add")
@nodeType("663")
@insertZeroKey(true)
SELECT
     0 AS "DIM_ALL_DATATYPES_DEMO_KEY",
     "COL_NUMBER" AS "COL_NUMBER",
     "COL_DECIMAL" AS "COL_DECIMAL",
     "COL_INT" AS "COL_INT",
     "COL_FLOAT" AS "COL_FLOAT",
     "COL_DOUBLE" AS "COL_DOUBLE",
     "COL_BOOLEAN" AS "COL_BOOLEAN",
     "COL_VARCHAR" AS "COL_VARCHAR",
     "COL_STRING" AS "COL_STRING",
     "COL_CHAR" AS "COL_CHAR",
     "COL_TEXT" AS "COL_TEXT",
     "COL_DATE" AS "COL_DATE",
     "COL_TIME" AS "COL_TIME",
     "COL_TIMESTAMP" AS "COL_TIMESTAMP",
     "COL_TIMESTAMP_NTZ" AS "COL_TIMESTAMP_NTZ",
     "COL_TIMESTAMP_LTZ" AS "COL_TIMESTAMP_LTZ",
     "COL_TIMESTAMP_TZ" AS "COL_TIMESTAMP_TZ",
     "COL_BINARY" AS "COL_BINARY",
     "COL_VARIANT" AS "COL_VARIANT",
     "COL_OBJECT" AS "COL_OBJECT",
     "COL_ARRAY" AS "COL_ARRAY",
     "COL_GEOGRAPHY" AS "COL_GEOGRAPHY",
     "COL_GEOMETRY" AS "COL_GEOMETRY",
     "COL_XML" AS "COL_XML",
     1 AS "SYSTEM_VERSION",
     'Y' AS "SYSTEM_CURRENT_FLAG",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE",
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE"
FROM {{ ref('SRC', 'ALL_DATATYPES_DEMO') }} "ALL_DATATYPES_DEMO"