@id("a1c9a6ba-f904-44bf-93be-9532f918e4c4")
@nodeType("663")
@insertZeroKey(true)
@lastModifiedCompToggle(true)
@lastModifiedColumn("[object Object]")
SELECT
     0 AS "DIM_NATION_TEST_LM_SCD1_KEY",
     "N_NATIONKEY" AS "N_NATIONKEY" @nullable(false),
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     1 AS "SYSTEM_VERSION",
     'Y' AS "SYSTEM_CURRENT_FLAG",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE",
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE"
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"