@id("02d8dce1-774f-4af0-896f-42afdb41f5f4")
@nodeType("4a720337-2713-45a5-b3f2-2d47d7abe3e5")
SELECT DISTINCT
    N_NATIONKEY AS "N_NATIONKEY" @isBusinessKey,
    N_NAME AS "N_NAME",
    N_REGIONKEY AS "N_REGIONKEY",
    N_COMMENT AS "N_COMMENT",
    N_LOAD_TIMESTAMP AS "N_LOAD_TIMESTAMP",
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate
FROM {{ ref("SRC", "NATION_TEST") }} "NATION_TEST_ALIAS"