@id("441c8705-4e5e-4376-b5ce-dc4f8ca56126")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")

@materializationType("view")

WITH ALL_NATIONS AS (

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY1') }}

    UNION ALL

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY2') }}

)

SELECT
     NATIONS_SAMPLE."N_NATIONKEY" AS "N_NATIONKEY",
     NATIONS_SAMPLE."N_NAME" AS "N_NAME",
     NATIONS_SAMPLE."N_REGIONKEY" AS "N_REGIONKEY",
     NATIONS_SAMPLE."N_COMMENT" AS "N_COMMENT",
     NATIONS_SAMPLE."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" @isLastModifiedColumn
FROM ALL_NATIONS "NATIONS_SAMPLE"