@id("00c30f6b-5905-4c4f-8112-2549c60d052d")
@nodeType("e35d8015-545b-4150-942f-5168dcd2bea8")

WITH ALL_NATIONS AS (

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY1') }}

    UNION ALL

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY2') }}

)

SELECT
     0 AS "DIM_KEY" @isSurrogateKey,
     NATIONS_SAMPLE."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     NATIONS_SAMPLE."N_NAME" AS "N_NAME",
     NATIONS_SAMPLE."N_REGIONKEY" AS "N_REGIONKEY",
     NATIONS_SAMPLE."N_COMMENT" AS "N_COMMENT",
     NATIONS_SAMPLE."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     0 AS "VERSION" @isSystemVersion,
     '' AS "FLAG" @isSystemCurrentFlag,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP_LTZ(9)) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP_LTZ(9)) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate
FROM ALL_NATIONS "NATIONS_SAMPLE"
