@id("2cac3f85-b2ed-4f5c-af0e-58e1423c8b1e")
@nodeType("707")
SELECT
     "O_ORDERKEY" AS "O_ORDERKEY",
     "O_CUSTKEY" AS "O_CUSTKEY",
     "O_ORDERSTATUS" AS "O_ORDERSTATUS",
     "O_TOTALPRICE" AS "O_TOTALPRICE",
     "O_ORDERDATE" AS "O_ORDERDATE",
     "O_ORDERPRIORITY" AS "O_ORDERPRIORITY",
     "O_CLERK" AS "O_CLERK",
     "O_SHIPPRIORITY" AS "O_SHIPPRIORITY",
     "O_COMMENT" AS "O_COMMENT"
FROM {{ ref('SRC', 'ORDERS') }} "ORDERS"