@id("a8a16a5f-68ef-47bb-9b49-d0852497e6b6")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")

@type2Dimension

WITH ALL_TABLES AS (
     SELECT * FROM {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1"
     UNION
     SELECT * FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
)

SELECT
     ALL_TABLES."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     ALL_TABLES."N_NAME" AS "N_NAME" @isBusinessKey,
     ALL_TABLES."N_REGIONKEY" AS "N_REGIONKEY",
     ALL_TABLES."N_COMMENT" AS "N_COMMENT",
     ALL_TABLES."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" @isLastModifiedColumn,
     "DIM_MS_LM_SCD2_KEY"::NUMBER AS "FCT_MS_LM_SCD2_KEY" @isSurrogateKey,
     "SYSTEM_CURRENT_FLAG"::VARCHAR AS "SYSTEM_CURRENT_FLAG" @isSystemCurrentFlag,
     "SYSTEM_VERSION"::NUMBER AS "SYSTEM_VERSION" @isSystemVersion,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE" @isSystemEndDate
FROM ALL_TABLES