@id("701381d4-fe1e-4242-ba24-23558a414b4e")
@nodeType("704")
SELECT
     "SALES_ID" AS "SALES_ID",
     "SALESPERSON" AS "SALESPERSON",
     "SALE_DATE" AS "SALE_DATE",
     "AMOUNT" AS "AMOUNT",
     "QUARTER" AS "QUARTER",
     "REGION" AS "REGION"
FROM {{ ref('TARGET', 'RAW_SALES') }} "RAW_SALES"