@id("4cd7b05e-69b0-4a32-85ed-1e22f846d2a1")
@nodeType("6fda2820-4404-4b60-bad3-cf0edd7dab92")
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY",
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     UPPER("N_COMMENT") AS "N_COMMENT_UPPER",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"