@id("777854f3-7974-4873-93ef-03c0d70d58a0")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")

SELECT
     NATION_COPY1."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     NATION_COPY1."N_NAME" AS "N_NAME",
     NATION_COPY1."N_REGIONKEY" AS "N_REGIONKEY",
     NATION_COPY1."N_COMMENT" AS "N_COMMENT",
     NATION_COPY1."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate
FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
INNER JOIN {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1"
ON "NATION_COPY2".N_NATIONKEY = "NATION_COPY1".N_NATIONKEY