@id("99182268-c84a-43b3-99ff-461aa9d23e70")
@nodeType("707")
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY",
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     "UPDATE_TIME" AS "UPDATE_TIME"
FROM {{ ref('SRC', 'NATION') }} "NATION"