@id("88fe935f-0351-4cf9-94d4-d9c0d5628392")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")

@zeroKey("string:DEFAULT", "number:10", "boolean:True", "datetime:1900-01-01 00:00:00.000")

SELECT
     ALL_DATATYPES_DEMO."COL_NUMBER" AS "COL_NUMBER" @isBusinessKey,
     ALL_DATATYPES_DEMO."COL_DECIMAL" AS "COL_DECIMAL",
     ALL_DATATYPES_DEMO."COL_INT" AS "COL_INT" @isChangeTracking,
     ALL_DATATYPES_DEMO."COL_FLOAT" AS "COL_FLOAT",
     ALL_DATATYPES_DEMO."COL_DOUBLE" AS "COL_DOUBLE",
     ALL_DATATYPES_DEMO."COL_BOOLEAN" AS "COL_BOOLEAN",
     ALL_DATATYPES_DEMO."COL_VARCHAR" AS "COL_VARCHAR",
     ALL_DATATYPES_DEMO."COL_STRING" AS "COL_STRING",
     ALL_DATATYPES_DEMO."COL_CHAR" AS "COL_CHAR",
     ALL_DATATYPES_DEMO."COL_TEXT" AS "COL_TEXT",
     ALL_DATATYPES_DEMO."COL_DATE" AS "COL_DATE",
     ALL_DATATYPES_DEMO."COL_TIME" AS "COL_TIME",
     ALL_DATATYPES_DEMO."COL_TIMESTAMP" AS "COL_TIMESTAMP",
     ALL_DATATYPES_DEMO."COL_TIMESTAMP_NTZ" AS "COL_TIMESTAMP_NTZ",
     ALL_DATATYPES_DEMO."COL_TIMESTAMP_LTZ" AS "COL_TIMESTAMP_LTZ",
     ALL_DATATYPES_DEMO."COL_TIMESTAMP_TZ" AS "COL_TIMESTAMP_TZ",
     ALL_DATATYPES_DEMO."COL_BINARY" AS "COL_BINARY",
     ALL_DATATYPES_DEMO."COL_OBJECT" AS "COL_OBJECT",
     ALL_DATATYPES_DEMO."COL_ARRAY" AS "COL_ARRAY",
     ALL_DATATYPES_DEMO."COL_GEOGRAPHY" AS "COL_GEOGRAPHY" @isChangeTracking,
     ALL_DATATYPES_DEMO."COL_GEOMETRY" AS "COL_GEOMETRY" @isChangeTracking,
     '' AS "SYSTEM_CURRENT_FLAG" @isSystemCurrentFlag,
     1 AS "SYSTEM_VERSION" @isSystemVersion,
     0 AS "MRG_ALL_DATATYPES_DEMO_KEY" @isSurrogateKey @zeroKey(0),
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate,
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE" @isSystemEndDate
FROM {{ ref('SRC', 'ALL_DATATYPES_DEMO') }} "ALL_DATATYPES_DEMO"