@id("93a56bee-3cb5-4de0-9589-67796f5d3c6f")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")


WITH ALL_NATIONS AS (

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY1') }}

    UNION ALL

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_COPY2') }}

)

SELECT
     ALL_NATIONS."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     ALL_NATIONS."N_NAME" AS "N_NAME",
     ALL_NATIONS."N_REGIONKEY" AS "N_REGIONKEY",
     ALL_NATIONS."N_COMMENT" AS "N_COMMENT",
     ALL_NATIONS."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate
FROM ALL_NATIONS