@id("b91da9f1-d0a4-49ae-9d7c-223341457c6d")
@nodeType("6fda2820-4404-4b60-bad3-cf0edd7dab92")


WITH ALL_NATIONS AS (

    SELECT N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT, N_LOAD_TIMESTAMP
    FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"
    ASOF JOIN {{ ref('SRC', 'REGION_HISTORY') }} "REG"
    MATCH_CONDITION(
        NATION_TEST."N_LOAD_TIMESTAMP" >= REG."LOAD_TIMESTAMP"
    )
    ON NATION_TEST."N_REGIONKEY" = REG."REGIONKEY"
)

SELECT * from ALL_NATIONS