@id("725aeb7f-cbd3-48a6-83a4-9919ac07f9bd")
@nodeType("659")
@orderby(true)
@orderbycolumn("[object Object]", "desc")
@groupByAll(true)
@description("table''adkfh")
WITH ALL_NATIONS AS(
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY" ,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" 
FROM {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1" 
UNION
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY" ,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
) 
SELECT
     ALL_NATIONS."N_NATIONKEY" AS "N_NATIONKEY"  @nullable(false) @isBusinessKey,
     ALL_NATIONS."N_NAME" AS "N_NAME" @defaultValue("NA"),
     ALL_NATIONS."N_REGIONKEY" AS "N_REGIONKEY" @description("Column''desc"),
     ALL_NATIONS."N_COMMENT" AS "N_COMMENT",
     ALL_NATIONS."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" ,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE"
FROM ALL_NATIONS "ALL_NATIONS"
WHERE ALL_NATIONS.N_NATIONKEY = 2 