@id("fccd78d3-0a38-4cc1-9987-83452459661f")
@nodeType("663")
@insertZeroKey(true)
@lastModifiedCompToggle(true)
@type2Dimension(true)
@lastModifiedColumn("[object Object]")
SELECT
     0 AS "DIM_NATION_TEST_LM_SCD2_KEY",
     NATION_TEST."N_NATIONKEY" AS "N_NATIONKEY" @nullable(false),
     NATION_TEST."N_NAME" AS "N_NAME",
     NATION_TEST."N_REGIONKEY" AS "N_REGIONKEY",
     NATION_TEST."N_COMMENT" AS "N_COMMENT",
     NATION_TEST."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     1 AS "SYSTEM_VERSION",
     'Y' AS "SYSTEM_CURRENT_FLAG",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE",
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE"
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"