@id("07368c8d-209b-4845-954a-597539e86369")
@nodeType("659")
@orderby(true)
@orderbycolumn("[object Object]", "desc")
@lastModifiedCompToggle(true)
@lastModifiedColumn("[object Object]")
@groupByAll(true)
WITH ALL_NATIONS AS(
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY" ,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" 
FROM {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1" 
UNION
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY" ,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
) 
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY"  @nullable(false),
     "N_NAME" AS "N_NAME" @defaultValue("NA"),
     "N_REGIONKEY" AS "N_REGIONKEY" @description("Column''desc"),
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE"
FROM ALL_NATIONS "ALL_NATIONS"
WHERE N_NATIONKEY = 2