@id("2cf7951f-2e02-411e-b540-cc21cf3f7985")
@nodeType("660")
@groupByAll(true)
@orderby(true)
@orderbycolumn("N_NAME", "desc")
@lastModifiedCompToggle(true)
@lastModifiedColumn("N_LOAD_TIMESTAMP")
@type2Dimension(true)
SELECT
     0 AS "PSTG_NATION_TEST_KEY",
     "N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     1 AS "SYSTEM_VERSION",
     'Y' AS "SYSTEM_CURRENT_FLAG",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE",
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE"
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"