@id("70998834-f8bb-4d84-88d1-697ff758646b")
@nodeType("e35d8015-545b-4150-942f-5168dcd2bea8")


SELECT
     "N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     "N_NATIONKEY" AS "N_NATIONKEY",
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
INNER JOIN {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1"
ON "NATION_COPY2".N_NATIONKEY = "NATION_COPY1".N_NATIONKEY