@id("a1e03825-d974-4a50-8fe2-0637a3c6a618")
@nodeType("663")
@lastModifiedCompToggle(true)
@type2Dimension(true)

SELECT
     0 AS "DIM_NATION_TEST_KEY",
     NATION_TEST."N_NATIONKEY" AS "N_NATIONKEY" @hashValue("GH_COL1","GH_COL2"),
     NATION_TEST."N_NAME" AS "N_NAME",
     NATION_TEST."N_REGIONKEY" AS "N_REGIONKEY" @hashValue("GH_COL1"),
     NATION_TEST."N_COMMENT" AS "N_COMMENT",
     NATION_TEST."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     {{ get_hash('GH_COL1') }}::STRING AS "GH_COLUMN1",
     {{ get_hash('GH_COL2') }}::STRING AS "GH_COLUMN2",
     1 AS "SYSTEM_VERSION",
     'Y' AS "SYSTEM_CURRENT_FLAG",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE",
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE"
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"