@id("033e763c-d084-4cfd-a839-0fdc8a8a1d6a")
@nodeType("659")
SELECT
     "COL_NUMBER" AS "COL_NUMBER",
     "COL_DECIMAL" AS "COL_DECIMAL",
     "COL_INT" AS "COL_INT",
     "COL_FLOAT" AS "COL_FLOAT",
     "COL_DOUBLE" AS "COL_DOUBLE",
     "COL_VARCHAR" AS "COL_VARCHAR",
     "COL_STRING" AS "COL_STRING",
     "COL_CHAR" AS "COL_CHAR",
     "COL_TEXT" AS "COL_TEXT",
     "COL_DATE" AS "COL_DATE",
     "COL_TIME" AS "COL_TIME",
     "COL_TIMESTAMP" AS "COL_TIMESTAMP",
     "COL_TIMESTAMP_NTZ" AS "COL_TIMESTAMP_NTZ",
     "COL_TIMESTAMP_LTZ" AS "COL_TIMESTAMP_LTZ",
     "COL_TIMESTAMP_TZ" AS "COL_TIMESTAMP_TZ",
     "COL_BINARY" AS "COL_BINARY",
     "COL_VARIANT" AS "COL_VARIANT",
     "COL_OBJECT" AS "COL_OBJECT",
     "COL_ARRAY" AS "COL_ARRAY",
     "COL_GEOGRAPHY" AS "COL_GEOGRAPHY",
     "COL_GEOMETRY" AS "COL_GEOMETRY",
     "COL_XML" AS "COL_XML",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE"
FROM {{ ref('SRC', 'ALL_DATATYPES_DEMO') }} "ALL_DATATYPES_DEMO"