@id("a2211d69-f8a8-4253-95ca-91a35752777b")
@nodeType("ece2dca8-2416-4db4-b6ae-e12dfb4de042")
@type2Dimension(true)
@lastModifiedCompToggle(true)
@insertZeroKey(true)

SELECT
     NATION_TEST."N_NATIONKEY" AS "N_NATIONKEY",
     NATION_TEST."N_NAME" AS "N_NAME",
     NATION_TEST."N_REGIONKEY" AS "N_REGIONKEY",
     NATION_TEST."N_COMMENT" AS "N_COMMENT",
     NATION_TEST."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP" @isLastModifiedColumn,
     NATION_TEST."LM_SCD2_KEY"::NUMBER AS "LM_SCD2_KEY" @isSurrogateKey,
     "SYSTEM_CURRENT_FLAG"::VARCHAR AS "SYSTEM_CURRENT_FLAG" @isSystemCurrentFlag,
     "SYSTEM_VERSION"::NUMBER AS "SYSTEM_VERSION" @isSystemVersion,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE" @isSystemEndDate
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"