@id("d1e4473b-c5fb-4458-9ddb-954f7de8ef2b")
@nodeType("704")
@materializationType("view")
SELECT
     "EMAIL" AS "EMAIL",
     "JOIN_DATE" AS "JOIN_DATE",
     "AGE_BAND" AS "AGE_BAND",
     "HOUSEHOLD_INCOME" AS "HOUSEHOLD_INCOME",
     "MARITAL_STATUS" AS "MARITAL_STATUS",
     "HOUSEHOLD_SIZE" AS "HOUSEHOLD_SIZE",
     "TOTAL_ORDER_VALUE" AS "TOTAL_ORDER_VALUE"
FROM {{ ref('SRC', 'CUSTOMERS') }} "CUSTOMERS"