@id("842827e9-8bb0-4f0d-9d65-fa64fa646670")
@nodeType("704")
WITH "ORDER_COUNTS" AS (
    SELECT
        MOD("ORDER_ID", 25) AS "NATION_KEY",
        COUNT(*) AS "ORDER_COUNT"
    FROM {{ ref('SRC', 'ORDERS_TEST') }}
    GROUP BY MOD("ORDER_ID", 25)
)
SELECT
     "NATION_KEY" AS "NATION_KEY",
     "ORDER_COUNT" AS "ORDER_COUNT"
FROM "ORDER_COUNTS"