@id("be9d19cf-2c79-4a28-9667-5a930db47f92")
@nodeType("e35d8015-545b-4150-942f-5168dcd2bea8")


SELECT
     NATION_TEST."N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     NATION_TEST."N_NAME" AS "N_NAME" @isChangeTracking,
     NATION_TEST."N_REGIONKEY" AS "N_REGIONKEY",
     NATION_TEST."N_COMMENT" AS "N_COMMENT",
     NATION_TEST."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     '' AS "SYSTEM_CURRENT_FLAG" @isSystemCurrentFlag,
     1 AS "SYSTEM_VERSION" @isSystemVersion,
     0 AS "MRG_NATION_TEST_KEY" @isSurrogateKey,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE" @isSystemCreateDate,
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE" @isSystemUpdateDate,
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE" @isSystemEndDate
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"