@id("fccdb2c3-9b9f-4ffb-b4e7-59ccc0cccc88")
@nodeType("6fda2820-4404-4b60-bad3-cf0edd7dab92")


SELECT
     NATION_COPY2."N_NATIONKEY" AS "N_NATIONKEY",
     NATION_COPY1."N_NAME" AS "N_NAME",
     NATION_COPY1."N_REGIONKEY" AS "N_REGIONKEY",
     NATION_COPY1."N_COMMENT" AS "N_COMMENT",
     NATION_COPY1."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
INNER JOIN {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1"
ON "NATION_COPY2".N_NATIONKEY = "NATION_COPY1".N_NATIONKEY