@id("cfc74200-d538-4bbd-bd3d-ac3c1129c15d")
@nodeType("710")
SELECT DISTINCT
     0 AS "DIM_NATION_TEST1_KEY",
     "N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     1 AS "SYSTEM_VERSION",
     'Y' AS "SYSTEM_CURRENT_FLAG",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE",
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE"
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"