@id("740512ba-8e6c-415a-a589-1077be34ec9e")
@nodeType("230cba1d-908f-4198-b597-1cef53279d36")
SELECT
     "N_NATIONKEY" AS "N_NATIONKEY" @isBusinessKey,
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     "N_NATIONKEY" AS "N_NATIONKEY",
     "N_NAME" AS "N_NAME",
     "N_REGIONKEY" AS "N_REGIONKEY",
     "N_COMMENT" AS "N_COMMENT",
     "N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION_COPY2') }} "NATION_COPY2"
INNER JOIN {{ ref('SRC', 'NATION_COPY1') }} "NATION_COPY1"
ON "NATION_COPY2".N_NATIONKEY = "NATION_COPY1".N_NATIONKEY