@id("02b07a56-40a1-403b-9d34-4e66e809ff58")
@nodeType("663")
SELECT
     0 AS "DIM_NATION_TEST1_KEY",
     NATION_TEST_ALIAS."N_NATIONKEY" AS "N_NATIONKEY",
     NATION_TEST_ALIAS."N_NAME" AS "N_NAME",
     NATION_TEST_ALIAS."N_REGIONKEY" AS "N_REGIONKEY",
     NATION_TEST_ALIAS."N_COMMENT" AS "N_COMMENT",
     NATION_TEST_ALIAS."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP",
     1 AS "SYSTEM_VERSION",
     'Y' AS "SYSTEM_CURRENT_FLAG",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_CREATE_DATE",
     CAST(CURRENT_TIMESTAMP AS TIMESTAMP) AS "SYSTEM_UPDATE_DATE",
     CAST('2999-12-31 00:00:00' AS TIMESTAMP) AS "SYSTEM_END_DATE"
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST_ALIAS"