@id("b8275bee-ffd3-4825-8f98-aaf2220432cf")
@nodeType("6fda2820-4404-4b60-bad3-cf0edd7dab92")


SELECT
     NATION_TEST."N_NATIONKEY" AS "N_NATIONKEY",
     NATION_TEST."N_NAME" AS "N_NAME",
     NATION_TEST."N_REGIONKEY" AS "N_REGIONKEY",
     NATION_TEST."N_COMMENT" AS "N_COMMENT",
     NATION_TEST."N_LOAD_TIMESTAMP" AS "N_LOAD_TIMESTAMP"
FROM {{ ref('SRC', 'NATION_TEST') }} "NATION_TEST"
ASOF JOIN {{ ref('SRC', 'REGION_HISTORY') }} "REG"
MATCH_CONDITION(
    NATION_TEST."N_LOAD_TIMESTAMP" >= REG."LOAD_TIMESTAMP"
)
ON NATION_TEST."N_REGIONKEY" = REG."REGIONKEY"